# .github/pr-agent-config.yaml

pr_agent:
  enabled: true
  llm_provider: openai

  openai:
    api_key: $OPENAI_API_KEY
    model: gpt-4o
    temperature: 0.4
    
  code_review_prompt:
    - "Please evaluate the code in terms of readability."
    - "Indicate whether the functions follow the single-responsibility principle."
    - "Explain if there are any potential security vulnerabilities in the code."
    - "Respond in Turkish."
    - "Start your comment with: 'Ben bir geyiğim.' (I am a deer.)"
  
  general_prompt:
    - "What is the purpose of this PR? Summarize it."
    - "Evaluate the impact of the code changes on the overall system."
