name: VPN Connection Test
on:
  push:
    branches:
      - master
jobs:
  test-vpn:
    runs-on: ubuntu-latest
    steps:
      - name: Pritunl Client GitHub Action
        uses: nathanielvarona/pritunl-client-github-action@v1
        with:
          profile-file: ${{secrets.PREPROD_VPN_CRED}}
